test4

diff --git a/.github/workflows/local-libraries.yml b/.github/workflows/local-libraries.yml
--- a/.github/workflows/local-libraries.yml
+++ b/.github/workflows/local-libraries.yml
@@ -31,12 +31,16 @@ jobs:
 
       - name: Build Libraries
         run: |
-          for LIB in transaction-search web3-login; do
-            npx ng build $LIB
-            if [ $? -ne 0 ]; then
-              echo "Error building $LIB!"
-              exit 1
+          for LIB_DIR in projects/*; do
+            if [[ -d $LIB_DIR ]]; then
+              LIB_NAME=$(basename $LIB_DIR)
+              echo "Building $LIB_NAME..."
+              npx ng build $LIB_NAME
+              if [ $? -ne 0 ]; then
+                echo "Error building $LIB_NAME!"
+                exit 1
+              fi
+              echo "$LIB_NAME built successfully!"
             fi
-            echo "$LIB built successfully!"
           done
       
